# wbl-frontend/k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wbl-frontend-service
spec:
  type: ClusterIP
  selector:
    app: wbl-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
